version: '3.6'
services:
  qaaro-frontend:
    image: docker.qaaro-frontend
    container_name: qaaro-frontend-container
    ports:
      - "3000:3000"
    restart: always
    networks:
      - lb-net

  qaaro-frontend-dev:
    image: docker.qaaro-frontend-dev
    container_name: qaaro-frontend-container-dev
    ports:
      - "3001:3000"
    restart: always
    networks:
      - lb-net

networks:
  lb-net:
    name: lb-net
    external: true
