version: '3.6'
services:
  qaaro:
    image: docker.qaaro
    container_name: qaaro-container
    ports:
      - "5000:5000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # volumes:
    #   - qaaro-data
    networks:
      - lb-net
    expose:
      - 5000
    depends_on:
      - mongodb
      # - redis

  qaaro-dev:
    image: docker.qaaro-dev
    container_name: qaaro-container-dev
    ports:
      - "5001:5000"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # volumes:
    #   - qaaro-data
    networks:
      - lb-net
    expose:
      - 5001
    depends_on:
      - mongodb-dev
      # - redis-dev

  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    networks:
      - lb-net
    ports:
      - 27017:27017
    restart: always
    env_file:
      - .env
    volumes:
      - /root/qaaro/db/data:/data/db

  mongodb-dev:
    image: mongo:latest
    container_name: mongodb-dev
    hostname: mongodb-dev
    networks:
      - lb-net
    ports:
      - 27018:27017
    restart: always
    env_file:
      - .env
    volumes:
      - /root/qaaro-dev/db/data:/data/db 

  # redis:
  #   image: redis:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #   restart: always
  #   networks:
  #     - lb-net

  # redis-dev:
  #   image: redis:latest
  #   container_name: redis-dev
  #   ports:
  #     - "6380:6379"
  #   restart: always
  #   networks:
  #     - lb-net

networks:
  lb-net:
    name: lb-net
    external: true